// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SantiyeAPI.Data;

#nullable disable

namespace SantiyeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260220211502_YeniKurulum")]
    partial class YeniKurulum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("IsciSantiye", b =>
                {
                    b.Property<int>("IscilerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SantiyelerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IscilerId", "SantiyelerId");

                    b.HasIndex("SantiyelerId");

                    b.ToTable("IsciSantiye");
                });

            modelBuilder.Entity("SantiyeAPI.Models.Avans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OdemeTuru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SantiyeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IsciId");

                    b.HasIndex("SantiyeId");

                    b.ToTable("Avanslar");
                });

            modelBuilder.Entity("SantiyeAPI.Models.GunlukKayit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CalismaKatsayisi")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("IsciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SantiyeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Yevmiye")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IsciId");

                    b.HasIndex("SantiyeId");

                    b.ToTable("GunlukKayitlar");
                });

            modelBuilder.Entity("SantiyeAPI.Models.Isci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GunlukUcret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TcNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Isciler");
                });

            modelBuilder.Entity("SantiyeAPI.Models.Santiye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Konum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Santiyeler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "A Şantiyesi (Merkez)",
                            AktifMi = true,
                            Konum = "İstanbul"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "B Şantiyesi (Toki Konutları)",
                            AktifMi = true,
                            Konum = "Ankara"
                        });
                });

            modelBuilder.Entity("IsciSantiye", b =>
                {
                    b.HasOne("SantiyeAPI.Models.Isci", null)
                        .WithMany()
                        .HasForeignKey("IscilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantiyeAPI.Models.Santiye", null)
                        .WithMany()
                        .HasForeignKey("SantiyelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SantiyeAPI.Models.Avans", b =>
                {
                    b.HasOne("SantiyeAPI.Models.Isci", "Isci")
                        .WithMany("Avanslar")
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantiyeAPI.Models.Santiye", "Santiye")
                        .WithMany()
                        .HasForeignKey("SantiyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Isci");

                    b.Navigation("Santiye");
                });

            modelBuilder.Entity("SantiyeAPI.Models.GunlukKayit", b =>
                {
                    b.HasOne("SantiyeAPI.Models.Isci", "Isci")
                        .WithMany("GunlukKayitlar")
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SantiyeAPI.Models.Santiye", "Santiye")
                        .WithMany()
                        .HasForeignKey("SantiyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Isci");

                    b.Navigation("Santiye");
                });

            modelBuilder.Entity("SantiyeAPI.Models.Isci", b =>
                {
                    b.Navigation("Avanslar");

                    b.Navigation("GunlukKayitlar");
                });
#pragma warning restore 612, 618
        }
    }
}
