// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SantiyeAPI.Data;

#nullable disable

namespace SantiyeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AllowedActiveSiteCount")
                        .HasColumnType("integer");

                    b.Property<string>("DamgaHash")
                        .HasColumnType("text");

                    b.Property<string>("DonanimKimligi")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SonIslemTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Patron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("KasaId")
                        .HasColumnType("integer");

                    b.Property<int?>("SorumluOlduguSantiyeId")
                        .HasColumnType("integer");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KasaId");

                    b.HasIndex("SorumluOlduguSantiyeId");

                    b.ToTable("Patronlar");
                });

            modelBuilder.Entity("SantiyeAPI.Models.Avans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("IsciId")
                        .HasColumnType("integer");

                    b.Property<int>("KasaId")
                        .HasColumnType("integer");

                    b.Property<string>("OdemeTuru")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("OdendiMi")
                        .HasColumnType("boolean");

                    b.Property<int?>("SantiyeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IsciId");

                    b.HasIndex("KasaId");

                    b.HasIndex("SantiyeId");

                    b.HasIndex("Tarih", "OdendiMi");

                    b.ToTable("Avanslar", (string)null);
                });

            modelBuilder.Entity("SantiyeAPI.Models.GunlukKayit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<decimal>("CalismaKatsayisi")
                        .HasColumnType("decimal(3,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("IsciId")
                        .HasColumnType("integer");

                    b.Property<bool>("OdendiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("SantiyeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Yevmiye")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IsciId");

                    b.HasIndex("IsciId", "SantiyeId", "Tarih")
                        .IsUnique()
                        .HasDatabaseName("UX_GunlukKayit_TekKayitZirhi")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("SantiyeId", "Tarih", "OdendiMi");

                    b.ToTable("GunlukKayitlar", (string)null);
                });

            modelBuilder.Entity("SantiyeAPI.Models.HarcamaKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("HarcamaKategorileri");
                });

            modelBuilder.Entity("SantiyeAPI.Models.Isci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("GunlukUcret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Meslek")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TcNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character(11)")
                        .IsFixedLength();

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("TcNo")
                        .IsUnique();

                    b.HasIndex("Ad", "Soyad");

                    b.ToTable("Isciler", (string)null);
                });

            modelBuilder.Entity("SantiyeAPI.Models.Kasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Kasalar");
                });

            modelBuilder.Entity("SantiyeAPI.Models.KasaHareketi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("HareketTipi")
                        .HasColumnType("integer");

                    b.Property<int?>("IptalEdilenIslemId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("KasaId")
                        .HasColumnType("integer");

                    b.Property<int?>("PatronId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReferansId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferansTabloAdi")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("SantiyeId")
                        .HasColumnType("integer");

                    b.Property<bool>("SifirlamaFisiMi")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("TransferGrupId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Yon")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IptalEdilenIslemId");

                    b.HasIndex("PatronId");

                    b.HasIndex("SantiyeId");

                    b.HasIndex("KasaId", "IslemTarihi");

                    b.HasIndex("ReferansTabloAdi", "ReferansId", "IsDeleted")
                        .HasDatabaseName("IX_KasaHareket_Referans");

                    b.ToTable("KasaHareketleri", null, t =>
                        {
                            t.HasCheckConstraint("CK_KasaHareketi_Tutar_Pozitif", "\"Tutar\" > 0");
                        });
                });

            modelBuilder.Entity("SantiyeAPI.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdSoyad = "Muhammet Zeki",
                            KullaniciAdi = "ahmetfurkan",
                            Rol = "Sef",
                            Sifre = "$2a$11$p.PApCHcjKiXJn8E3SflfOxlwxhcyYAEHr2ExFokjknFeJXaRuLY2"
                        });
                });

            modelBuilder.Entity("SantiyeAPI.Models.KullanilanSifre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("KullanımTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Sifre")
                        .IsUnique()
                        .HasDatabaseName("UX_KullanilanSifre_TekKullanimZirhi");

                    b.ToTable("KullanilanSifreler");
                });

            modelBuilder.Entity("SantiyeAPI.Models.MaasGecmisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("IsciId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Yevmiye")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IsciId", "BaslangicTarihi");

                    b.ToTable("MaasGecmisleri", (string)null);
                });

            modelBuilder.Entity("SantiyeAPI.Models.MaasOdemesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("IsciId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("KasaId")
                        .HasColumnType("integer");

                    b.Property<int?>("SantiyeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IsciId");

                    b.HasIndex("KasaId");

                    b.HasIndex("SantiyeId");

                    b.ToTable("MaasOdemeleri", (string)null);
                });

            modelBuilder.Entity("SantiyeAPI.Models.Santiye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Konum")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("LisansBitisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Ad");

                    b.HasIndex("CompanyId");

                    b.ToTable("Santiyeler", (string)null);
                });

            modelBuilder.Entity("SantiyeAPI.Models.SantiyeIsci", b =>
                {
                    b.Property<int>("IsciId")
                        .HasColumnType("integer");

                    b.Property<int>("SantiyeId")
                        .HasColumnType("integer");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AyrilmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("KatilmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("IsciId", "SantiyeId");

                    b.HasIndex("SantiyeId");

                    b.HasIndex("IsciId", "AktifMi");

                    b.ToTable("SantiyeIsciler");
                });

            modelBuilder.Entity("SantiyeAPI.Models.SantiyeIsciGecmisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArsivlenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("AyrilmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IsciId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("KatilmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SantiyeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SantiyeIsciGecmisleri");
                });

            modelBuilder.Entity("SantiyeAPI.Models.SantiyeNotu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NotMetni")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("SantiyeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SantiyeId");

                    b.HasIndex("Tarih");

                    b.ToTable("SantiyeNotlari");
                });

            modelBuilder.Entity("SantiyeAPI.Models.SatinAlmaGecmisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlinanJetonSayisi")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<decimal>("OdenenTutar")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("SatinAlmaGecmisleri");
                });

            modelBuilder.Entity("Patron", b =>
                {
                    b.HasOne("SantiyeAPI.Models.Kasa", "Kasa")
                        .WithMany()
                        .HasForeignKey("KasaId");

                    b.HasOne("SantiyeAPI.Models.Santiye", "SorumluOlduguSantiye")
                        .WithMany()
                        .HasForeignKey("SorumluOlduguSantiyeId");

                    b.Navigation("Kasa");

                    b.Navigation("SorumluOlduguSantiye");
                });

            modelBuilder.Entity("SantiyeAPI.Models.Avans", b =>
                {
                    b.HasOne("SantiyeAPI.Models.Isci", "Isci")
                        .WithMany("Avanslar")
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SantiyeAPI.Models.Kasa", "Kasa")
                        .WithMany()
                        .HasForeignKey("KasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantiyeAPI.Models.Santiye", "Santiye")
                        .WithMany()
                        .HasForeignKey("SantiyeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Isci");

                    b.Navigation("Kasa");

                    b.Navigation("Santiye");
                });

            modelBuilder.Entity("SantiyeAPI.Models.GunlukKayit", b =>
                {
                    b.HasOne("SantiyeAPI.Models.Isci", "Isci")
                        .WithMany("GunlukKayitlar")
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SantiyeAPI.Models.Santiye", "Santiye")
                        .WithMany()
                        .HasForeignKey("SantiyeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Isci");

                    b.Navigation("Santiye");
                });

            modelBuilder.Entity("SantiyeAPI.Models.KasaHareketi", b =>
                {
                    b.HasOne("SantiyeAPI.Models.KasaHareketi", "IptalEdilenIslem")
                        .WithMany()
                        .HasForeignKey("IptalEdilenIslemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SantiyeAPI.Models.Kasa", "Kasa")
                        .WithMany("Hareketler")
                        .HasForeignKey("KasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Patron", "Patron")
                        .WithMany("Harcamalar")
                        .HasForeignKey("PatronId");

                    b.HasOne("SantiyeAPI.Models.Santiye", "Santiye")
                        .WithMany()
                        .HasForeignKey("SantiyeId");

                    b.Navigation("IptalEdilenIslem");

                    b.Navigation("Kasa");

                    b.Navigation("Patron");

                    b.Navigation("Santiye");
                });

            modelBuilder.Entity("SantiyeAPI.Models.KullanilanSifre", b =>
                {
                    b.HasOne("Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SantiyeAPI.Models.MaasGecmisi", b =>
                {
                    b.HasOne("SantiyeAPI.Models.Isci", "Isci")
                        .WithMany("MaasGecmisleri")
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Isci");
                });

            modelBuilder.Entity("SantiyeAPI.Models.MaasOdemesi", b =>
                {
                    b.HasOne("SantiyeAPI.Models.Isci", "Isci")
                        .WithMany()
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantiyeAPI.Models.Kasa", "Kasa")
                        .WithMany()
                        .HasForeignKey("KasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SantiyeAPI.Models.Santiye", "Santiye")
                        .WithMany()
                        .HasForeignKey("SantiyeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Isci");

                    b.Navigation("Kasa");

                    b.Navigation("Santiye");
                });

            modelBuilder.Entity("SantiyeAPI.Models.Santiye", b =>
                {
                    b.HasOne("Company", "Company")
                        .WithMany("Santiyeler")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SantiyeAPI.Models.SantiyeIsci", b =>
                {
                    b.HasOne("SantiyeAPI.Models.Isci", "Isci")
                        .WithMany("SantiyeIsciler")
                        .HasForeignKey("IsciId");

                    b.HasOne("SantiyeAPI.Models.Santiye", "Santiye")
                        .WithMany("SantiyeIsciler")
                        .HasForeignKey("SantiyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Isci");

                    b.Navigation("Santiye");
                });

            modelBuilder.Entity("SantiyeAPI.Models.SantiyeNotu", b =>
                {
                    b.HasOne("SantiyeAPI.Models.Santiye", "Santiye")
                        .WithMany("Notlari")
                        .HasForeignKey("SantiyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Santiye");
                });

            modelBuilder.Entity("Company", b =>
                {
                    b.Navigation("Santiyeler");
                });

            modelBuilder.Entity("Patron", b =>
                {
                    b.Navigation("Harcamalar");
                });

            modelBuilder.Entity("SantiyeAPI.Models.Isci", b =>
                {
                    b.Navigation("Avanslar");

                    b.Navigation("GunlukKayitlar");

                    b.Navigation("MaasGecmisleri");

                    b.Navigation("SantiyeIsciler");
                });

            modelBuilder.Entity("SantiyeAPI.Models.Kasa", b =>
                {
                    b.Navigation("Hareketler");
                });

            modelBuilder.Entity("SantiyeAPI.Models.Santiye", b =>
                {
                    b.Navigation("Notlari");

                    b.Navigation("SantiyeIsciler");
                });
#pragma warning restore 612, 618
        }
    }
}
